### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TheSin-** [nopnop2002/Raspberry-93Cx6#6]
This isn't an issue, it's a question about main.c

If I run this it looks like it'll wipe it. org8Mode and org16Mode, seem to wipe before it reads, is this the case?  And if so why?

I need to read mine to screen, then figure out what values to change.  I was hoping to use main to just dump the data without writing anything to start with, then write a new version to just add the changes I need to the eeprom.

since both the mentioned functions start with

```
  // erase/write enable
  eeprom_ew_enable(dev);

  // erase all memory
  eeprom_erase_all(dev);

  // write same data
  eeprom_write_all(dev, 0x00);
```

before it even reads, this makes me a little nervous.

**Comment by ewpa** [comment]
Yes, tested and confirmed.  EEPROM is wiped and overwritten with some pattern.  So you'll need to copy ```main.c``` and change to suit your needs.
